import serviceImage from '@/assets//Images/servicesImage.png';
import consultationLogo from '@/assets/Logos/consultationLogo.webp';
import mentalHealthLogo from '@/assets/Logos/mentalHealthLogo.png';
import specializedServicesLogo from '@/assets/Logos/specializedServicesLogo.png';

export const links = ['Home', 'Services', 'About', 'Contact'];

export const cardNums = [
  {
    num: '24/7',
    text: 'Availability',
  },
  {
    num: '0 seconds',
    text: 'Waiting time',
  },
  {
    num: '0$',
    text: 'Free of charge',
  },
  {
    num: 'Reliability',
    text: 'Advanced AI Accurate Analysis',
  },
];

export const ServicesData = [
  {
    img: consultationLogo,
    title: 'General Consultation',
    id: 'generalconsultation',
    heading: 'General Consultation',
    texts: [
      'Access medical advice any time of the day.',
      'Enter symptoms and get an initial assessment.',
      'Ask general health-related questions and receive answers.',
    ],
  },
  {
    img: mentalHealthLogo,
    title: 'Mental Health Support',
    id: 'mentalhealthsupport',
    heading: 'Mental Health Support',
    texts: [
      'Conduct self-assessments for mental well-being.',
      'Access resources and support for mental health.',
      'Get immediate assistance during mental health crises.',
    ],
  },
  {
    img: specializedServicesLogo,
    title: 'Specialized Services',
    id: 'specializedservices',
    heading: 'Specialized Services',
    texts: [
      'Get second opinions on diagnoses and treatment plans.',
      'Receive referrals to specialists based on health conditions.',
      'Explore alternative and complementary medicine options.',
    ],
  },
];

export const InformationBannerData = {
  heading: 'We Are Always Here To Ensure Best Medical Consulting',
  texts: [
    'Easy and simple chatting',
    '24/7 Service',
    'Suitable for everyone',
    'Accurate Analysis',
  ],
  img: serviceImage,
};

export const defaultSession = {
  chat_id: '-1',
  user: '',
  messages: [],
  createdAt: null,
};

export const medicalProperties = {
  Allergies: [
    'Peanuts',
    'Tree Nuts',
    'Milk',
    'Eggs',
    'Fish',
    'Shellfish',
    'Soy',
    'Wheat',
    'Sesame',
    'Mustard',
    'Sulphites',
    'Lupin',
    'Celery',
    'Mollusks',
    'Pollen',
    'Dust Mites',
    'Mold',
    'Animal Dander',
    'Latex',
    'Certain Medications',
    'Insect Stings',
    'Nickel',
    'Fragrances',
    'Cockroaches',
    'Grapes',
    'Apples',
    'Bananas',
    'Tomatoes',
    'Strawberries',
    'Raspberries',
    'Carrots',
    'Onions',
    'Garlic',
    'Citrus Fruits',
    'Avocado',
    'Zucchini',
    'Peas',
    'Corn',
    'Beef',
    'Pork',
    'Chicken',
    'Turkey',
    'Lamb',
    'Goat',
    'Seaweed',
    'Yeast',
    'Poppy Seeds',
    'Chili Peppers',
    'Cinnamon',
    'Vanilla',
    'Chocolate',
    'Coffee',
    'Tea',
    'Dairy',
    'Alcohol',
    'Honey',
    'Coconut',
    'Basil',
    'Mint',
    'Rosemary',
    'Thyme',
    'Oregano',
    'Coriander',
    'Paprika',
    'Turmeric',
    'Saffron',
  ],
  Chronic: [
    'Diabetes',
    'Hypertension',
    'Asthma',
    'Chronic Obstructive Pulmonary Disease (COPD)',
    'Heart Disease',
    'Chronic Kidney Disease',
    'Arthritis',
    'Inflammatory Bowel Disease (IBD)',
    'Multiple Sclerosis',
    "Parkinson's Disease",
    'Epilepsy',
    'Chronic Fatigue Syndrome',
    'Fibromyalgia',
    'Chronic Migraines',
    'Sickle Cell Disease',
    'Lupus',
    'Psoriasis',
    'Rheumatoid Arthritis',
    'Gout',
    'Chronic Sinusitis',
    'Chronic Back Pain',
    'Sleep Apnea',
    'Endometriosis',
    'Cystic Fibrosis',
    'Autoimmune Hepatitis',
    "Graves' Disease",
    "Hashimoto's Thyroiditis",
    'Bipolar Disorder',
    'Major Depressive Disorder',
    'Schizophrenia',
    'Anxiety Disorder',
    'Attention Deficit Hyperactivity Disorder (ADHD)',
    "Alzheimer's Disease",
    'Dementia',
    'HIV/AIDS',
    'Tuberculosis',
    'Chronic Bronchitis',
    'Interstitial Cystitis',
    'Chronic Pancreatitis',
    'Epileptic Seizures',
    'Peripheral Artery Disease',
  ],
  Medication: [
    'Insulin',
    'Metformin',
    'Lisinopril',
    'Amlodipine',
    'Atorvastatin',
    'Levothyroxine',
    'Aspirin',
    'Ibuprofen',
    'Acetaminophen',
    'Amoxicillin',
    'Prednisone',
    'Omeprazole',
    'Gabapentin',
    'Albuterol',
    'Hydrochlorothiazide',
    'Clopidogrel',
    'Losartan',
    'Cetirizine',
    'Epinephrine',
    'Diazepam',
    'Hydrocodone',
    'Oxycodone',
    'Loratadine',
    'Dextromethorphan',
    'Lorazepam',
    'Naproxen',
    'Zoloft',
    'Lexapro',
    'Prozac',
    'Cymbalta',
    'Wellbutrin',
    'Tramadol',
    'Tamsulosin',
    'Ranitidine',
    'Simvastatin',
    'Diltiazem',
    'Verapamil',
    'Methotrexate',
    'Azithromycin',
    'Cephalexin',
    'Ciprofloxacin',
    'Vancomycin',
    'Hydroxychloroquine',
    'Sildenafil',
    'Tadalafil',
    'Nitroglycerin',
    'Warfarin',
    'Heparin',
    'Furosemide',
    'Spironolactone',
    'Digoxin',
    'Amiodarone',
    'Methadone',
    'Buprenorphine',
    'Hydroxyzine',
    'Clonazepam',
  ],
  Lifestyle: [
    'Regular Exercise',
    'Healthy Diet',
    'Smoking',
    'Alcohol Consumption',
    'Sleep Hygiene',
    'Stress Management',
    'Weight Management',
    'Hydration',
    'Recreational Activities',
    'Hobbies and Interests',
    'Work-life Balance',
    'Social Interaction',
    'Mindfulness and Meditation',
    'Preventive Health Care',
  ],
  ConditionsAndSurgeries: [
    'Appendectomy',
    'Cholecystectomy',
    'Hysterectomy',
    'Coronary Bypass Surgery',
    'Knee Replacement Surgery',
    'Hip Replacement Surgery',
    'Cataract Surgery',
    'Tonsillectomy',
    'Sinus Surgery',
    'Prostatectomy',
    'Laparoscopic Surgery',
    'Angioplasty',
    'Bariatric Surgery',
    'Lung Surgery',
    'Back Surgery',
    'Orthopedic Surgery',
    'Cesarean Section',
    'Skin Biopsy',
    'Spinal Fusion',
    'Endoscopy',
    'Colonoscopy',
    'Gallbladder Removal',
    'Breast Biopsy',
    'Cardiac Pacemaker Implant',
    'Hemorrhoidectomy',
    'Urethral Sling Surgery',
    'Laparotomy',
    'Surgical Debridement',
    'Arthroscopy',
    'Vasectomy',
    'Ovarian Cyst Removal',
    'Rhinoplasty',
    'Facelift',
    'Dental Implants',
    'Root Canal Treatment',
    'Endometrial Ablation',
    'Ventriculoperitoneal Shunt',
    'Bunion Surgery',
    'Cochlear Implant',
    'Hip Arthroscopy',
    'Shoulder Reconstruction Surgery',
    'Corneal Transplant',
    'Neck Discectomy',
    'Scoliosis Surgery',
    'Bladder Sling Surgery',
    'Thyroidectomy',
    'Lung Biopsy',
    'Meniscus Repair',
    'Ankle Surgery',
    'Laparoscopic Hernia Repair',
  ],
};

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];

